create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 80),
  color text not null default '#e58b54',
  created_at timestamptz not null default now()
);

create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  habit_id bigint not null references public.habits(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  logged_on date not null default current_date,
  completed boolean not null default false,
  unique (habit_id, logged_on)
);

alter table public.habits enable row level security;
alter table public.daily_logs enable row level security;

drop policy if exists "Users can select their own habits" on public.habits;
create policy "Users can select their own habits"
  on public.habits for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own habits" on public.habits;
create policy "Users can insert their own habits"
  on public.habits for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own habits" on public.habits;
create policy "Users can update their own habits"
  on public.habits for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own habits" on public.habits;
create policy "Users can delete their own habits"
  on public.habits for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select their own daily logs" on public.daily_logs;
create policy "Users can select their own daily logs"
  on public.daily_logs for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own daily logs" on public.daily_logs;
create policy "Users can insert their own daily logs"
  on public.daily_logs for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own daily logs" on public.daily_logs;
create policy "Users can update their own daily logs"
  on public.daily_logs for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own daily logs" on public.daily_logs;
create policy "Users can delete their own daily logs"
  on public.daily_logs for delete
  using (auth.uid() = user_id);

-- Seeds the first registered account with sample data when the script is run again.
insert into public.habits (user_id, name, color)
select users.id, seed.name, seed.color
from (select id from auth.users order by created_at limit 1) as users
cross join (values
  ('Drink water', '#e58b54'),
  ('Read for 20 minutes', '#5e8f82'),
  ('Stretch', '#d7a84c')
) as seed(name, color)
where not exists (
  select 1 from public.habits existing where existing.user_id = users.id
);

insert into public.daily_logs (habit_id, user_id, logged_on, completed)
select habits.id, habits.user_id, current_date, true
from public.habits
where habits.user_id = (select id from auth.users order by created_at limit 1)
  and not exists (
    select 1 from public.daily_logs logs
    where logs.habit_id = habits.id and logs.logged_on = current_date
  );